# ============================================================================
# Trading Alerts SaaS V7 - Aider Configuration
# ============================================================================
# This file configures Aider to work autonomously with MiniMax M2 API
# following our 6 policy documents for consistent, high-quality code generation.
#
# Last Updated: 2025-11-09
# ============================================================================

# ============================================================================
# MODEL CONFIGURATION
# ============================================================================
# MiniMax M2 is configured as the default model
# ~80% cheaper than GPT-4 while maintaining quality

# Main model for code generation (MiniMax M2)
model: openai/MiniMax-M2

# Editor model for smaller edits
editor-model: openai/MiniMax-M2

# Weak model for simple tasks (summaries, commit messages)
weak-model: openai/MiniMax-M2

# Note: Set OPENAI_API_KEY and OPENAI_API_BASE in your environment:
# set OPENAI_API_KEY=your_minimax_api_key
# set OPENAI_API_BASE=https://api.minimax.io/v1

# ============================================================================
# ENVIRONMENT FILE
# ============================================================================
# Load API keys from .env file automatically
env-file: .env

# ============================================================================
# AUTO-COMMIT SETTINGS
# ============================================================================

# Enable auto-commits after successful code generation
# Set to false for interactive testing, true for autonomous mode
auto-commits: false

# Commit message template
# Aider will use this format for commit messages
# commit-prompt: |
#   Write a concise commit message following conventional commits format.
#   Format: <type>(<scope>): <description>
#   Types: feat, fix, docs, style, refactor, test, chore
#   Include validation results in commit body.

# Require attribution in commits
attribute-author: true
attribute-committer: true

# ============================================================================
# POLICY DOCUMENTS (READ-ONLY)
# ============================================================================
# These files guide Aider's decision-making but should never be modified

read:
  # Core policy documents (PRIMARY GUIDANCE)
  - docs/policies/01-approval-policies.md
  - docs/policies/02-quality-standards.md
  - docs/policies/03-architecture-rules.md
  - docs/policies/04-escalation-triggers.md
  - docs/policies/05-coding-patterns.md
  - docs/policies/06-aider-instructions.md

  # Architecture and structure documentation
  - ARCHITECTURE.md
  - DOCKER.md
  - docs/v5-structure-division.md
  - phase_milestones_v7_minimax.md

  # Tier specifications
  - docs/policies/00-tier-specifications.md

  # OpenAPI specifications (source of truth)
  - trading_alerts_openapi.yaml
  - docs/flask_mt5_openapi.yaml

  # Seed code examples (reference only)
  - seed-code/market_ai_engine.py

  # Project overview
  - README.md

  # Progress tracking (Aider updates this, but reads for context)
  - PROGRESS.md

# ============================================================================
# SEED CODE (REFERENCE ONLY - READ-ONLY)
# ============================================================================
# Seed code provides patterns to learn from, but is never modified

# Automatically read seed code when relevant
# Note: Add specific seed files here that Aider should reference
# Example:
# - seed-code/trading-alerts-bolt-2/app/api/example/route.ts
# - seed-code/trading-alerts-saas-v4/components/example.tsx

# ============================================================================
# GIT CONFIGURATION
# ============================================================================

# Use git for version control
git: true

# Automatically add new files to git
gitignore: true

# Show git diffs before committing
show-diffs: true

# ============================================================================
# EDITING BEHAVIOR
# ============================================================================

# Editing format (whole file, diff, or udiff)
# "diff" is more efficient for large files
edit-format: diff

# Enable code streaming (faster feedback)
stream: true

# Show repository map for context
map-tokens: 2048

# Use universal ctags for better code navigation
# Disabled: may cause issues if ctags not installed
# use-ctags: false  # Not supported in config file for this version

# ============================================================================
# VALIDATION & TESTING
# ============================================================================

# Run linting checks
# Disabled: may cause issues if linter not configured
lint: false

# Run tests after changes (if available)
# test-cmd: npm test

# Lint command (if you want Aider to auto-lint)
# lint-cmd: npm run lint

# ============================================================================
# CHAT SETTINGS
# ============================================================================

# Enable chat history
chat-history-file: .aider.chat.history.md

# Save input history
input-history-file: .aider.input.history

# Enable pretty output with colors
pretty: true

# Show token usage for cost tracking
show-model-warnings: true

# ============================================================================
# FILE HANDLING
# ============================================================================

# Note: auto-add and ignore are not supported in .aider.conf.yml for v0.86.1
# Use .aiderignore file instead for ignoring files
# Use command-line arguments to add specific files

# Automatically add commonly needed files
# auto-add:
#   - "*.ts"
#   - "*.tsx"
#   - "*.py"
#   - "*.yaml"
#   - "*.yml"
#   - "*.json"
#   - "*.md"

# Ignore patterns (in addition to .gitignore)
# ignore:
#   - node_modules/
#   - .next/
#   - dist/
#   - build/
#   - __pycache__/
#   - "*.pyc"
#   - .env
#   - .env.local

# ============================================================================
# ADVANCED SETTINGS
# ============================================================================

# Number of context messages to keep
max-chat-history: 100

# Enable suggestions from Aider
suggest-shell-commands: true

# Enable voice input (if supported)
# voice: false

# Dark mode for terminal output
dark-mode: true

# ============================================================================
# ENVIRONMENT VARIABLES (Set these in your shell, NOT here!)
# ============================================================================
# Required for MiniMax M2:
#   OPENAI_API_KEY=your_minimax_api_key_here
#   OPENAI_API_BASE=https://api.minimax.io/v1
#
# MiniMax uses OpenAI-compatible API, so set these two variables.
# Do NOT use MINIMAX_API_KEY - only OPENAI_API_KEY and OPENAI_API_BASE.
#
# Optional (for the app itself):
#   DATABASE_URL=postgresql://...
#   NEXT_PUBLIC_API_URL=http://localhost:3000
#
# Never commit API keys! Keep them in .env (which is gitignored)
# ============================================================================

# ============================================================================
# USAGE INSTRUCTIONS
# ============================================================================
#
# Basic Commands:
# ---------------
# Start Aider:
#   aider
#
# Add files to chat:
#   /add app/api/example/route.ts
#   /add components/example.tsx
#
# Read policy files (already auto-loaded from 'read' section above):
#   Policies are automatically available as context
#
# Ask Aider to implement:
#   "Implement GET /api/alerts following Pattern 1 from 05-coding-patterns.md"
#   "Create the tier validation utility from 03-architecture-rules.md"
#
# Check validation:
#   "Validate the code with Claude Code and show results"
#
# Commit:
#   /commit
#   (or auto-commits if auto-commits: true)
#
# See help:
#   /help
#
# Exit:
#   /exit
#
# ============================================================================
# WORKFLOW EXAMPLE (from 06-aider-instructions.md)
# ============================================================================
#
# 1. Start Aider:
#    $ aider
#
# 2. Aider loads policy files automatically (from 'read' section)
#
# 3. Tell Aider what to build:
#    You: "Implement Part 1: Foundation & Root Configuration"
#
# 4. Aider follows 7-step workflow:
#    - Read Requirements (policies, OpenAPI, seed code)
#    - Plan Implementation
#    - Generate Code
#    - Validate with Claude Code
#    - Decide (approve/fix/escalate)
#    - Act (commit or fix)
#    - Update PROGRESS.md
#
# 5. Aider reports progress every 3 files
#
# 6. If escalation needed, Aider asks you for decision
#
# ============================================================================
# TROUBLESHOOTING
# ============================================================================
#
# Issue: "Model not found"
# Fix: Ensure MINIMAX_API_KEY or OPENAI_API_KEY is set and model name is correct
#
# Issue: "Policy files not loading"
# Fix: Check that 'read' paths are correct (relative to project root)
#
# Issue: "Auto-commits not working"
# Fix: Ensure git is initialized and auto-commits: true
#
# Issue: "Aider too slow"
# Fix: Reduce map-tokens or use lighter weak-model
#
# Issue: "Validation failing"
# Fix: Ensure Claude Code is available and OPENAI_API_KEY is set
#
# ============================================================================
