# ============================================================================
# Trading Alerts SaaS V7 - Aider Configuration (MiniMax M2 Optimized)
# ============================================================================
# This file configures Aider to work with MiniMax M2 API using a rotation
# strategy to stay within the 204,800 token context window limit.
#
# Last Updated: 2025-11-21
# Context Window: 204,800 tokens (MiniMax M2)
# Base Load: ~129,000 tokens (compressed policies + architecture)
# Available for Dynamic Loading: ~75,000 tokens
# ============================================================================

# ============================================================================
# MODEL CONFIGURATION
# ============================================================================
# MiniMax M2 via OpenAI-compatible endpoint

# Main model for code generation
model: openai/MiniMax-M2

# Editor model for smaller edits
editor-model: openai/MiniMax-M2

# Weak model for simple tasks
weak-model: openai/MiniMax-M2

# Note: Set these environment variables:
# OPENAI_API_KEY=your_minimax_api_key
# OPENAI_API_BASE=https://api.minimax.io/v1

# ============================================================================
# ENVIRONMENT FILE
# ============================================================================
env-file: .env

# ============================================================================
# AUTO-COMMIT SETTINGS
# ============================================================================
auto-commits: false
attribute-author: true
attribute-committer: true

# ============================================================================
# CORE POLICY DOCUMENTS (ALWAYS LOADED - BASE: ~79k tokens)
# ============================================================================
# These compressed files provide essential guidance for all development
# NEVER remove these from the base load - they're required for quality

read:
  # ========== COMPRESSED POLICY FILES (79k tokens) ==========
  # These were compressed by Claude Code to reduce token usage
  # Original: 139k → Compressed: 79k (43% reduction)
  
  - docs/policies/01-approval-policies-compress.md        # 9,491 tokens
  - docs/policies/02-quality-standards.md                 # 9,818 tokens (not compressed, small)
  - docs/policies/03-architecture-rules-compress.md       # 11,326 tokens
  - docs/policies/04-escalation-triggers-compress.md      # 7,430 tokens
  - docs/policies/05-coding-patterns-compress.md          # 20,999 tokens
  - docs/policies/06-aider-instructions.md                # 10,966 tokens (not compressed)
  - docs/policies/07-dlocal-integration-rules-compress.md # 6,870 tokens
  - docs/policies/00-tier-specifications.md               # 2,479 tokens (not compressed, tiny)
  
  # ========== COMPRESSED OPENAPI SPEC (22k tokens) ==========
  # Primary API contract - always available
  
  - docs/trading_alerts_openapi_compress.yaml             # 21,690 tokens
  
  # ========== ARCHITECTURE & STRUCTURE (28k tokens) ==========
  # Project structure and architecture documentation
  
  - ARCHITECTURE.md                                        # ~10,000 tokens
  - README.md                                              # ~5,000 tokens
  - docs/v5-structure-division.md                          # ~10,000 tokens
  - docs/build-orders/README.md                            # ~3,000 tokens
  
  # --------------------------------------------------------------------------
  # TOTAL BASE LOAD: ~129,000 tokens
  # AVAILABLE FOR DYNAMIC LOADING: ~75,000 tokens
  # --------------------------------------------------------------------------

  # ========== ROTATION STRATEGY: PART-BY-PART LOADING ==========
  # Load these files ONLY when working on specific parts
  # Use /read-only and /drop commands to rotate files as needed
  #
  # CRITICAL: Do NOT uncomment multiple parts at once!
  # Load ONE part at a time, complete it, then move to next
  
  # ==========================================================================
  # PART 1: FOUNDATION & ROOT CONFIG (~11k tokens)
  # ==========================================================================
  # When building: 12 configuration files
  # /read-only docs/build-orders/part-01-foundation.md              # ~5k
  # /read-only docs/implementation-guides/v5_part_a.md              # ~6k
  
  # ==========================================================================
  # PART 2: DATABASE SCHEMA (~7k tokens)
  # ==========================================================================
  # When building: 4 database files
  # /read-only docs/build-orders/part-02-database.md                # ~3k
  # /read-only docs/implementation-guides/v5_part_b.md              # ~4k
  
  # ==========================================================================
  # PART 3: TYPE DEFINITIONS (~13k tokens)
  # ==========================================================================
  # When building: 6 type files
  # /read-only docs/build-orders/part-03-types.md                   # ~8k
  # /read-only docs/implementation-guides/v5_part_c.md              # ~5k
  
  # ==========================================================================
  # PART 4: TIER SYSTEM (~7k tokens)
  # ==========================================================================
  # When building: 4 tier management files
  # /read-only docs/build-orders/part-04-tier-system.md             # ~4k
  # /read-only docs/implementation-guides/v5_part_d.md              # ~3k
  
  # ==========================================================================
  # PART 5: AUTHENTICATION (~13k tokens)
  # ==========================================================================
  # When building: 19 authentication files (Google OAuth + credentials)
  # /read-only docs/build-orders/part-05-authentication.md          # ~2k
  # /read-only docs/implementation-guides/v5_part_e.md              # ~5k
  # /read-only docs/policies/08-google-oauth-implementation-rules.md # ~4k
  # /read-only docs/OAUTH_IMPLEMENTATION_READY.md                   # ~2k
  
  # ==========================================================================
  # PART 6: FLASK MT5 SERVICE (~16k tokens)
  # ==========================================================================
  # When building: 15 Flask microservice files
  # /read-only docs/build-orders/part-06-flask-mt5.md               # ~2k
  # /read-only docs/implementation-guides/v5_part_f.md              # ~4k
  # /read-only docs/flask_mt5_openapi.yaml                          # ~10k
  
  # ==========================================================================
  # PART 7: INDICATORS API (~6k tokens)
  # ==========================================================================
  # When building: 6 API route files
  # /read-only docs/build-orders/part-07-indicators-api.md          # ~2k
  # /read-only docs/implementation-guides/v5_part_g.md              # ~4k
  
  # ==========================================================================
  # PART 8: DASHBOARD (~6k tokens)
  # ==========================================================================
  # When building: 9 dashboard component files
  # /read-only docs/build-orders/part-08-dashboard.md               # ~2k
  # /read-only docs/implementation-guides/v5_part_h.md              # ~4k
  
  # ==========================================================================
  # PART 9: CHARTS (~6k tokens)
  # ==========================================================================
  # When building: 8 chart component files
  # /read-only docs/build-orders/part-09-charts.md                  # ~2k
  # /read-only docs/implementation-guides/v5_part_i.md              # ~4k
  
  # ==========================================================================
  # PART 10: WATCHLIST (~6k tokens)
  # ==========================================================================
  # When building: 8 watchlist files
  # /read-only docs/build-orders/part-10-watchlist.md               # ~2k
  # /read-only docs/implementation-guides/v5_part_j.md              # ~4k
  
  # ==========================================================================
  # PART 11: ALERTS (~6k tokens)
  # ==========================================================================
  # When building: 10 alert system files
  # /read-only docs/build-orders/part-11-alerts.md                  # ~2k
  # /read-only docs/implementation-guides/v5_part_k.md              # ~4k
  
  # ==========================================================================
  # PART 12: E-COMMERCE & BILLING (~7k tokens)
  # ==========================================================================
  # When building: 11 Stripe integration files
  # /read-only docs/build-orders/part-12-ecommerce.md               # ~2k
  # /read-only docs/implementation-guides/v5_part_l.md              # ~5k
  
  # ==========================================================================
  # PART 13: SETTINGS (~6k tokens)
  # ==========================================================================
  # When building: 17 settings page files
  # /read-only docs/build-orders/part-13-settings.md                # ~2k
  # /read-only docs/implementation-guides/v5_part_m.md              # ~4k
  
  # ==========================================================================
  # PART 14: ADMIN DASHBOARD (~6k tokens)
  # ==========================================================================
  # When building: 9 admin portal files
  # /read-only docs/build-orders/part-14-admin.md                   # ~2k
  # /read-only docs/implementation-guides/v5_part_n.md              # ~4k
  
  # ==========================================================================
  # PART 15: NOTIFICATIONS (~6k tokens)
  # ==========================================================================
  # When building: 9 notification system files
  # /read-only docs/build-orders/part-15-notifications.md           # ~2k
  # /read-only docs/implementation-guides/v5_part_o.md              # ~4k
  
  # ==========================================================================
  # PART 16: UTILITIES (~6k tokens)
  # ==========================================================================
  # When building: 25 utility files
  # /read-only docs/build-orders/part-16-utilities.md               # ~2k
  # /read-only docs/implementation-guides/v5_part_p.md              # ~4k
  
  # ==========================================================================
  # PART 17: AFFILIATE MARKETING (~26k tokens) WARNING: LARGE!
  # ==========================================================================
  # When building: 67 affiliate system files
  # BREAK INTO 4 SUB-SESSIONS (Files 1-11, 12-30, 31-49, 50-67)
  # /read-only docs/build-orders/part-17-affiliate.md               # ~2k
  # /read-only docs/implementation-guides/v5_part_r.md              # ~19k
  # /read-only docs/AFFILIATE-MARKETING-DESIGN.md                   # ~5k
  
  # ==========================================================================
  # PART 18: DLOCAL PAYMENTS (~28k tokens) WARNING: LARGE!
  # ==========================================================================
  # When building: 45 payment integration files
  # BREAK INTO 4 SUB-SESSIONS (Files 1-9, 10-18, 19-25, 26-37)
  # /read-only docs/build-orders/part-18-dlocal.md                  # ~2k
  # /read-only docs/implementation-guides/v5_part_r.md              # ~19k
  # /read-only docs/dlocal-openapi-endpoints.yaml                   # ~7k
  
  # ========== OTHER OPTIONAL FILES (Load when needed) ==========
  # These files can be loaded on-demand for reference
  
  # Other OpenAPI specs (load when working on specific APIs):
  # /read-only docs/flask_mt5_openapi.yaml                          # ~10k
  # /read-only docs/dlocal-openapi-endpoints.yaml                   # ~7k
  
  # Seed code (load specific files when referencing patterns):
  # /read-only seed-code/saas-starter/app/(login)/actions.ts
  # /read-only seed-code/v0-components/layouts/dashboard-layout.tsx
  # etc.
  
  # Progress tracking (automatically updated by Aider):
  - PROGRESS.md

# ============================================================================
# GIT CONFIGURATION
# ============================================================================
git: true
gitignore: true
show-diffs: true

# ============================================================================
# EDITING BEHAVIOR
# ============================================================================
edit-format: diff
stream: true
map-tokens: 512  # REDUCED to save context space

# ============================================================================
# CHAT SETTINGS
# ============================================================================
chat-history-file: .aider.chat.history.md
input-history-file: .aider.input.history
pretty: true
show-model-warnings: true

# ============================================================================
# ADVANCED SETTINGS
# ============================================================================
max-chat-history: 100
suggest-shell-commands: true
dark-mode: true

# ============================================================================
# USAGE INSTRUCTIONS - ROTATION WORKFLOW
# ============================================================================
#
# STEP 1: Start Aider
# --------------------
# > start-aider-anthropic.bat
#
# Base load will automatically include:
# - All 9 compressed policy files
# - Compressed OpenAPI spec
# - Architecture documentation
# - Build order README
#
# STEP 2: Load Part Files (ONE PART AT A TIME)
# ----------------------------------------------
# Example for Part 1:
# > /read-only docs/build-orders/part-01-foundation.md
# > /read-only docs/implementation-guides/v5_part_a.md
#
# STEP 3: Build Part
# ------------------
# > "Build Part 1 following the build order"
#
# Aider will:
# - Read build-orders/part-01-foundation.md
# - Follow file-by-file sequence
# - Use patterns from 05-coding-patterns-compress.md
# - Validate against all policies
# - Auto-commit if approved
#
# STEP 4: Rotate to Next Part
# ----------------------------
# > /drop docs/build-orders/part-01-foundation.md
# > /drop docs/implementation-guides/v5_part_a.md
# > /read-only docs/build-orders/part-02-database.md
# > /read-only docs/implementation-guides/v5_part_b.md
# > "Build Part 2 following the build order"
#
# STEP 5: Repeat for All Parts (1-18)
# ------------------------------------
# Continue rotating through parts until complete
#
# ============================================================================
# TROUBLESHOOTING
# ============================================================================
#
# Issue: "Context window exceeds limit"
# Fix: You loaded too many files. Use /drop to remove some.
#
# Issue: "Model not found"
# Fix: Check OPENAI_API_KEY and OPENAI_API_BASE are set correctly
#
# Issue: Aider can't find a file
# Fix: Use /read-only with correct relative path from project root
#
# Issue: Need to reference seed code
# Fix: /read-only seed-code/[path]/[file] temporarily, then /drop when done
#
# ============================================================================